# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.backlabel_2.setGeometry(QtCore.QRect(0, 0, 1031, 641))
        self.backlabel_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:0.267045, y2:0.272, stop:0 rgba(70, 174, 97, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10px;\n"
"")
        self.backlabel_2.setText("")
        self.backlabel_2.setObjectName("backlabel_2")
        self.frontlabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.frontlabel_3.setGeometry(QtCore.QRect(10, 10, 181, 481))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel_3.setFont(font)
        self.frontlabel_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(29, 255, 199), stop:1 rgb(81, 204, 112));\n"
"border-radius:15px;")
        self.frontlabel_3.setText("")
        self.frontlabel_3.setObjectName("frontlabel_3")
        self.Scraping = QtWidgets.QPushButton(self.centralwidget)
        self.Scraping.setGeometry(QtCore.QRect(20, 300, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Scraping.setFont(font)
        self.Scraping.setStyleSheet("QPushButton{\n"
"    background-color:rgb(44, 130, 134);\n"
"}\n"
"QPushButton:hover{\n"
"    color: #0000;\n"
"    background-color:rgb(85, 170, 127);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.Scraping.setFlat(True)
        self.Scraping.setObjectName("Scraping")
        self.heading_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.heading_label_3.setGeometry(QtCore.QRect(60, 70, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.heading_label_3.setFont(font)
        self.heading_label_3.setStyleSheet("color:(0,0,0,200);")
        self.heading_label_3.setObjectName("heading_label_3")
        self.Sorting = QtWidgets.QPushButton(self.centralwidget)
        self.Sorting.setGeometry(QtCore.QRect(20, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Sorting.setFont(font)
        self.Sorting.setStyleSheet("QPushButton{\n"
"    background-color:rgb(44, 130, 134);\n"
"}\n"
"QPushButton:hover{\n"
"    color: #0000;\n"
"    background-color:rgb(85, 170, 127);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.Sorting.setFlat(True)
        self.Sorting.setObjectName("Sorting")
        self.Searching = QtWidgets.QPushButton(self.centralwidget)
        self.Searching.setGeometry(QtCore.QRect(20, 240, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Searching.setFont(font)
        self.Searching.setStyleSheet("QPushButton{\n"
"    background-color:rgb(44, 130, 134);\n"
"}\n"
"QPushButton:hover{\n"
"    color: #0000;\n"
"    background-color:rgb(85, 170, 127);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.Searching.setFlat(True)
        self.Searching.setObjectName("Searching")
        self.frameSort = QtWidgets.QFrame(self.centralwidget)
        self.frameSort.setGeometry(QtCore.QRect(190, 0, 841, 501))
        self.frameSort.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSort.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSort.setObjectName("frameSort")
        self.lbl_logo = QtWidgets.QLabel(self.frameSort)
        self.lbl_logo.setGeometry(QtCore.QRect(260, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_logo.setFont(font)
        self.lbl_logo.setStyleSheet("color:rgb(0, 0, 0);\n"
"")
        self.lbl_logo.setObjectName("lbl_logo")
        self.frontlabel_2 = QtWidgets.QLabel(self.frameSort)
        self.frontlabel_2.setGeometry(QtCore.QRect(620, 10, 201, 481))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel_2.setFont(font)
        self.frontlabel_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(107, 255, 156), stop:1 rgb(121, 255, 251));\n"
"border-radius:15px;")
        self.frontlabel_2.setText("")
        self.frontlabel_2.setObjectName("frontlabel_2")
        self.btn_sort_2 = QtWidgets.QPushButton(self.frameSort)
        self.btn_sort_2.setGeometry(QtCore.QRect(640, 280, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_sort_2.setFont(font)
        self.btn_sort_2.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_sort_2.setObjectName("btn_sort_2")
        self.col_name = QtWidgets.QCheckBox(self.frameSort)
        self.col_name.setGeometry(QtCore.QRect(630, 150, 51, 21))
        self.col_name.setObjectName("col_name")
        self.col_trans = QtWidgets.QCheckBox(self.frameSort)
        self.col_trans.setGeometry(QtCore.QRect(720, 180, 81, 16))
        self.col_trans.setObjectName("col_trans")
        self.combo_algo_sort = QtWidgets.QComboBox(self.frameSort)
        self.combo_algo_sort.setGeometry(QtCore.QRect(690, 80, 121, 22))
        self.combo_algo_sort.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_algo_sort.setObjectName("combo_algo_sort")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.combo_algo_sort.addItem("")
        self.col_year = QtWidgets.QCheckBox(self.frameSort)
        self.col_year.setGeometry(QtCore.QRect(630, 180, 51, 21))
        self.col_year.setObjectName("col_year")
        self.label_14 = QtWidgets.QLabel(self.frameSort)
        self.label_14.setGeometry(QtCore.QRect(690, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.col_grade = QtWidgets.QCheckBox(self.frameSort)
        self.col_grade.setGeometry(QtCore.QRect(720, 150, 51, 21))
        self.col_grade.setObjectName("col_grade")
        self.radio_descend_sort = QtWidgets.QRadioButton(self.frameSort)
        self.radio_descend_sort.setGeometry(QtCore.QRect(720, 120, 82, 17))
        self.radio_descend_sort.setObjectName("radio_descend_sort")
        self.col_mileage = QtWidgets.QCheckBox(self.frameSort)
        self.col_mileage.setGeometry(QtCore.QRect(630, 210, 61, 21))
        self.col_mileage.setObjectName("col_mileage")
        self.btn_clr_sort_2 = QtWidgets.QPushButton(self.frameSort)
        self.btn_clr_sort_2.setGeometry(QtCore.QRect(720, 280, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_clr_sort_2.setFont(font)
        self.btn_clr_sort_2.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_clr_sort_2.setObjectName("btn_clr_sort_2")
        self.col_cc = QtWidgets.QCheckBox(self.frameSort)
        self.col_cc.setGeometry(QtCore.QRect(630, 240, 51, 21))
        self.col_cc.setObjectName("col_cc")
        self.col_link = QtWidgets.QCheckBox(self.frameSort)
        self.col_link.setGeometry(QtCore.QRect(720, 240, 61, 21))
        self.col_link.setObjectName("col_link")
        self.radio_ascend_sort = QtWidgets.QRadioButton(self.frameSort)
        self.radio_ascend_sort.setGeometry(QtCore.QRect(630, 120, 82, 17))
        self.radio_ascend_sort.setObjectName("radio_ascend_sort")
        self.col_fuel = QtWidgets.QCheckBox(self.frameSort)
        self.col_fuel.setGeometry(QtCore.QRect(720, 210, 41, 16))
        self.col_fuel.setObjectName("col_fuel")
        self.label_17 = QtWidgets.QLabel(self.frameSort)
        self.label_17.setGeometry(QtCore.QRect(630, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_22 = QtWidgets.QLabel(self.frameSort)
        self.label_22.setGeometry(QtCore.QRect(630, 370, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frameSort)
        self.label_23.setGeometry(QtCore.QRect(660, 410, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lbl_time_stat = QtWidgets.QLabel(self.frameSort)
        self.lbl_time_stat.setGeometry(QtCore.QRect(710, 400, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_time_stat.setFont(font)
        self.lbl_time_stat.setObjectName("lbl_time_stat")
        self.label_21 = QtWidgets.QLabel(self.frameSort)
        self.label_21.setGeometry(QtCore.QRect(630, 340, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lbl_algo_stat = QtWidgets.QLabel(self.frameSort)
        self.lbl_algo_stat.setGeometry(QtCore.QRect(710, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_algo_stat.setFont(font)
        self.lbl_algo_stat.setObjectName("lbl_algo_stat")
        self.btn_reset = QtWidgets.QPushButton(self.frameSort)
        self.btn_reset.setGeometry(QtCore.QRect(660, 450, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_reset.setFont(font)
        self.btn_reset.setStyleSheet("QPushButton {\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_reset.setObjectName("btn_reset")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(200, 120, 601, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frameSearch = QtWidgets.QFrame(self.centralwidget)
        self.frameSearch.setGeometry(QtCore.QRect(190, 0, 821, 501))
        self.frameSearch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSearch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSearch.setObjectName("frameSearch")
        self.widget_4 = QtWidgets.QWidget(self.frameSearch)
        self.widget_4.setGeometry(QtCore.QRect(150, 60, 321, 41))
        self.widget_4.setStyleSheet("background-color:rgb(69, 255, 49);\n"
"border-radius:80px;")
        self.widget_4.setObjectName("widget_4")
        self.txt_car_contains_2 = QtWidgets.QPlainTextEdit(self.widget_4)
        self.txt_car_contains_2.setGeometry(QtCore.QRect(10, 10, 211, 21))
        self.txt_car_contains_2.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:0px;")
        self.txt_car_contains_2.setObjectName("txt_car_contains_2")
        self.btn_car_contains = QtWidgets.QPushButton(self.widget_4)
        self.btn_car_contains.setGeometry(QtCore.QRect(230, 10, 75, 23))
        self.btn_car_contains.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(0,0,0);\n"
"color: rgb(255, 255, 255);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_car_contains.setObjectName("btn_car_contains")
        self.lbl_logo_2 = QtWidgets.QLabel(self.frameSearch)
        self.lbl_logo_2.setGeometry(QtCore.QRect(250, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_logo_2.setFont(font)
        self.lbl_logo_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"")
        self.lbl_logo_2.setObjectName("lbl_logo_2")
        self.frontlabel_4 = QtWidgets.QLabel(self.frameSearch)
        self.frontlabel_4.setGeometry(QtCore.QRect(620, 10, 201, 481))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel_4.setFont(font)
        self.frontlabel_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(107, 255, 156), stop:1 rgb(121, 255, 251));\n"
"border-radius:15px;")
        self.frontlabel_4.setText("")
        self.frontlabel_4.setObjectName("frontlabel_4")
        self.txt_not_col = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_not_col.setGeometry(QtCore.QRect(680, 361, 121, 16))
        self.txt_not_col.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_not_col.setObjectName("txt_not_col")
        self.txt_and_col = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_and_col.setGeometry(QtCore.QRect(680, 320, 121, 16))
        self.txt_and_col.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_and_col.setObjectName("txt_and_col")
        self.label_4 = QtWidgets.QLabel(self.frameSearch)
        self.label_4.setGeometry(QtCore.QRect(630, 150, 61, 21))
        self.label_4.setObjectName("label_4")
        self.btn_clr_search = QtWidgets.QPushButton(self.frameSearch)
        self.btn_clr_search.setGeometry(QtCore.QRect(730, 420, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_clr_search.setFont(font)
        self.btn_clr_search.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_clr_search.setObjectName("btn_clr_search")
        self.label_9 = QtWidgets.QLabel(self.frameSearch)
        self.label_9.setGeometry(QtCore.QRect(690, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.frameSearch)
        self.label_5.setGeometry(QtCore.QRect(630, 230, 41, 21))
        self.label_5.setObjectName("label_5")
        self.radio_not = QtWidgets.QCheckBox(self.frameSearch)
        self.radio_not.setGeometry(QtCore.QRect(630, 360, 51, 17))
        self.radio_not.setObjectName("radio_not")
        self.combo_attribute_search = QtWidgets.QComboBox(self.frameSearch)
        self.combo_attribute_search.setGeometry(QtCore.QRect(690, 110, 121, 22))
        self.combo_attribute_search.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_attribute_search.setObjectName("combo_attribute_search")
        self.label_6 = QtWidgets.QLabel(self.frameSearch)
        self.label_6.setGeometry(QtCore.QRect(630, 260, 41, 21))
        self.label_6.setObjectName("label_6")
        self.btn_search = QtWidgets.QPushButton(self.frameSearch)
        self.btn_search.setGeometry(QtCore.QRect(650, 420, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_search.setObjectName("btn_search")
        self.txt_col_contains = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_col_contains.setGeometry(QtCore.QRect(680, 230, 121, 21))
        self.txt_col_contains.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_col_contains.setObjectName("txt_col_contains")
        self.label_3 = QtWidgets.QLabel(self.frameSearch)
        self.label_3.setGeometry(QtCore.QRect(630, 110, 61, 21))
        self.label_3.setObjectName("label_3")
        self.radio_and = QtWidgets.QCheckBox(self.frameSearch)
        self.radio_and.setGeometry(QtCore.QRect(630, 320, 51, 17))
        self.radio_and.setObjectName("radio_and")
        self.txt_start_search = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_start_search.setGeometry(QtCore.QRect(680, 260, 121, 21))
        self.txt_start_search.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_start_search.setObjectName("txt_start_search")
        self.combo_algo_search = QtWidgets.QComboBox(self.frameSearch)
        self.combo_algo_search.setGeometry(QtCore.QRect(690, 150, 121, 22))
        self.combo_algo_search.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_algo_search.setObjectName("combo_algo_search")
        self.txt_end_search = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_end_search.setGeometry(QtCore.QRect(680, 290, 121, 21))
        self.txt_end_search.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_end_search.setObjectName("txt_end_search")
        self.label_11 = QtWidgets.QLabel(self.frameSearch)
        self.label_11.setGeometry(QtCore.QRect(630, 290, 41, 21))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.frameSearch)
        self.label_10.setGeometry(QtCore.QRect(640, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.radio_or = QtWidgets.QCheckBox(self.frameSearch)
        self.radio_or.setGeometry(QtCore.QRect(630, 340, 51, 17))
        self.radio_or.setObjectName("radio_or")
        self.txt_or_col = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_or_col.setGeometry(QtCore.QRect(680, 340, 121, 16))
        self.txt_or_col.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_or_col.setObjectName("txt_or_col")
        self.frameScrap = QtWidgets.QFrame(self.centralwidget)
        self.frameScrap.setGeometry(QtCore.QRect(190, 0, 827, 502))
        self.frameScrap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameScrap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameScrap.setObjectName("frameScrap")
        self.label_12 = QtWidgets.QLabel(self.frameScrap)
        self.label_12.setGeometry(QtCore.QRect(640, 60, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lbl_entites_scrapped = QtWidgets.QLabel(self.frameScrap)
        self.lbl_entites_scrapped.setGeometry(QtCore.QRect(790, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_entites_scrapped.setFont(font)
        self.lbl_entites_scrapped.setObjectName("lbl_entites_scrapped")
        self.txt_url = QtWidgets.QPlainTextEdit(self.frameScrap)
        self.txt_url.setGeometry(QtCore.QRect(630, 150, 191, 21))
        self.txt_url.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:0px;")
        self.txt_url.setObjectName("txt_url")
        self.label_8 = QtWidgets.QLabel(self.frameScrap)
        self.label_8.setGeometry(QtCore.QRect(630, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.btn_resume_scrap = QtWidgets.QPushButton(self.frameScrap)
        self.btn_resume_scrap.setGeometry(QtCore.QRect(730, 330, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_resume_scrap.setFont(font)
        self.btn_resume_scrap.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_resume_scrap.setObjectName("btn_resume_scrap")
        self.label_7 = QtWidgets.QLabel(self.frameScrap)
        self.label_7.setGeometry(QtCore.QRect(630, 120, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_pause_scrap = QtWidgets.QPushButton(self.frameScrap)
        self.btn_pause_scrap.setGeometry(QtCore.QRect(640, 330, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_pause_scrap.setFont(font)
        self.btn_pause_scrap.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_pause_scrap.setObjectName("btn_pause_scrap")
        self.btn_scrap = QtWidgets.QPushButton(self.frameScrap)
        self.btn_scrap.setGeometry(QtCore.QRect(690, 280, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_scrap.setFont(font)
        self.btn_scrap.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_scrap.setObjectName("btn_scrap")
        self.progressBar_scrap = QtWidgets.QProgressBar(self.frameScrap)
        self.progressBar_scrap.setGeometry(QtCore.QRect(630, 220, 181, 23))
        self.progressBar_scrap.setProperty("value", 24)
        self.progressBar_scrap.setObjectName("progressBar_scrap")
        self.lbl_logo_3 = QtWidgets.QLabel(self.frameScrap)
        self.lbl_logo_3.setGeometry(QtCore.QRect(250, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_logo_3.setFont(font)
        self.lbl_logo_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"")
        self.lbl_logo_3.setObjectName("lbl_logo_3")
        self.frontlabel_6 = QtWidgets.QLabel(self.frameScrap)
        self.frontlabel_6.setGeometry(QtCore.QRect(620, 20, 211, 471))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel_6.setFont(font)
        self.frontlabel_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(107, 255, 156), stop:1 rgb(121, 255, 251));\n"
"border-radius:15px;")
        self.frontlabel_6.setText("")
        self.frontlabel_6.setObjectName("frontlabel_6")
        self.scrap_table = QtWidgets.QTableWidget(self.frameScrap)
        self.scrap_table.setGeometry(QtCore.QRect(10, 120, 601, 361))
        self.scrap_table.setObjectName("scrap_table")
        self.scrap_table.setColumnCount(0)
        self.scrap_table.setRowCount(0)
        self.lbl_logo_3.raise_()
        self.frontlabel_6.raise_()
        self.label_12.raise_()
        self.lbl_entites_scrapped.raise_()
        self.txt_url.raise_()
        self.label_7.raise_()
        self.progressBar_scrap.raise_()
        self.label_8.raise_()
        self.btn_scrap.raise_()
        self.btn_resume_scrap.raise_()
        self.btn_pause_scrap.raise_()
        self.scrap_table.raise_()
        self.framemain = QtWidgets.QFrame(self.centralwidget)
        self.framemain.setGeometry(QtCore.QRect(190, 0, 841, 501))
        self.framemain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framemain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framemain.setObjectName("framemain")
        self.label = QtWidgets.QLabel(self.framemain)
        self.label.setGeometry(QtCore.QRect(150, 220, 521, 111))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.framemain)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 191, 111))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(self.framemain)
        self.label_13.setGeometry(QtCore.QRect(600, 100, 191, 111))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.framemain)
        self.label_15.setGeometry(QtCore.QRect(250, 360, 321, 111))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.backlabel_2.raise_()
        self.frontlabel_3.raise_()
        self.Scraping.raise_()
        self.heading_label_3.raise_()
        self.Sorting.raise_()
        self.Searching.raise_()
        self.tableWidget.raise_()
        self.frameSearch.raise_()
        self.frameScrap.raise_()
        self.framemain.raise_()
        self.frameSort.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Scraping.setText(_translate("MainWindow", "Scraping"))
        self.heading_label_3.setText(_translate("MainWindow", "Menu"))
        self.Sorting.setText(_translate("MainWindow", "Sorting"))
        self.Searching.setText(_translate("MainWindow", "Searching"))
        self.lbl_logo.setText(_translate("MainWindow", "Sorting"))
        self.btn_sort_2.setText(_translate("MainWindow", "Sort"))
        self.col_name.setText(_translate("MainWindow", "Name"))
        self.col_trans.setText(_translate("MainWindow", "Transmission"))
        self.combo_algo_sort.setItemText(0, _translate("MainWindow", "Merge Sort"))
        self.combo_algo_sort.setItemText(1, _translate("MainWindow", "Selection Sort "))
        self.combo_algo_sort.setItemText(2, _translate("MainWindow", "Insertion Sort"))
        self.combo_algo_sort.setItemText(3, _translate("MainWindow", "Bubble Sort"))
        self.combo_algo_sort.setItemText(4, _translate("MainWindow", "Quick Sort"))
        self.combo_algo_sort.setItemText(5, _translate("MainWindow", "Radix Sort"))
        self.combo_algo_sort.setItemText(6, _translate("MainWindow", "Bucket Sort"))
        self.combo_algo_sort.setItemText(7, _translate("MainWindow", "Counting Sort"))
        self.combo_algo_sort.setItemText(8, _translate("MainWindow", "Heap Sort"))
        self.combo_algo_sort.setItemText(9, _translate("MainWindow", "Comb Sort"))
        self.combo_algo_sort.setItemText(10, _translate("MainWindow", "Shell Sort"))
        self.col_year.setText(_translate("MainWindow", "Year"))
        self.label_14.setText(_translate("MainWindow", "Sorting"))
        self.col_grade.setText(_translate("MainWindow", "Grade"))
        self.radio_descend_sort.setText(_translate("MainWindow", "Descending"))
        self.col_mileage.setText(_translate("MainWindow", "Mileage"))
        self.btn_clr_sort_2.setText(_translate("MainWindow", "Clear"))
        self.col_cc.setText(_translate("MainWindow", "CC"))
        self.col_link.setText(_translate("MainWindow", "Link"))
        self.radio_ascend_sort.setText(_translate("MainWindow", "Ascending"))
        self.col_fuel.setText(_translate("MainWindow", "Fuel"))
        self.label_17.setText(_translate("MainWindow", "Algorithm"))
        self.label_22.setText(_translate("MainWindow", "Algorithm:"))
        self.label_23.setText(_translate("MainWindow", "Time:"))
        self.lbl_time_stat.setText(_translate("MainWindow", "__________"))
        self.label_21.setText(_translate("MainWindow", "Stats"))
        self.lbl_algo_stat.setText(_translate("MainWindow", "__________"))
        self.btn_reset.setText(_translate("MainWindow", "Reset Table"))
        self.btn_car_contains.setText(_translate("MainWindow", "Search "))
        self.lbl_logo_2.setText(_translate("MainWindow", "Searching"))
        self.label_4.setText(_translate("MainWindow", "Algorithm"))
        self.btn_clr_search.setText(_translate("MainWindow", "Clear"))
        self.label_9.setText(_translate("MainWindow", "Searching "))
        self.label_5.setText(_translate("MainWindow", "Contains"))
        self.radio_not.setText(_translate("MainWindow", "NOT"))
        self.label_6.setText(_translate("MainWindow", "Start as"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.label_3.setText(_translate("MainWindow", "Attribute"))
        self.radio_and.setText(_translate("MainWindow", "AND"))
        self.label_11.setText(_translate("MainWindow", "End as"))
        self.label_10.setText(_translate("MainWindow", "Filters"))
        self.radio_or.setText(_translate("MainWindow", "OR"))
        self.label_12.setText(_translate("MainWindow", "Entities Scrapped:"))
        self.lbl_entites_scrapped.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Progress:"))
        self.btn_resume_scrap.setText(_translate("MainWindow", "Resume"))
        self.label_7.setText(_translate("MainWindow", "URL:"))
        self.btn_pause_scrap.setText(_translate("MainWindow", "Pause"))
        self.btn_scrap.setText(_translate("MainWindow", "Scrap"))
        self.lbl_logo_3.setText(_translate("MainWindow", "Scraping"))
        self.label.setText(_translate("MainWindow", "Welcome to:\n"
"\n"
"           Stack Exchange Analysis🖥🎇"))
        self.label_2.setText(_translate("MainWindow", "🎈🎈🎈🎈🎈🎈"))
        self.label_13.setText(_translate("MainWindow", "🎈🎈🎈🎈🎈🎈"))
        self.label_15.setText(_translate("MainWindow", "🎉🎉🎉🎉🎉🎉🎉"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
