# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backlabel = QtWidgets.QLabel(self.centralwidget)
        self.backlabel.setGeometry(QtCore.QRect(0, 0, 1011, 511))
        self.backlabel.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:0.267045, y2:0.272, stop:0 rgba(70, 174, 97, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10px;\n"
"")
        self.backlabel.setText("")
        self.backlabel.setObjectName("backlabel")
        self.frontlabel = QtWidgets.QLabel(self.centralwidget)
        self.frontlabel.setGeometry(QtCore.QRect(10, 10, 171, 471))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel.setFont(font)
        self.frontlabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(29, 255, 199), stop:1 rgb(81, 204, 112));\n"
"border-radius:15px;")
        self.frontlabel.setText("")
        self.frontlabel.setObjectName("frontlabel")
        self.Searching = QtWidgets.QPushButton(self.centralwidget)
        self.Searching.setGeometry(QtCore.QRect(10, 230, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Searching.setFont(font)
        self.Searching.setStyleSheet("QPushButton{\n"
"    background-color:rgb(44, 130, 134);\n"
"}\n"
"QPushButton:hover{\n"
"    color: #0000;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgbargb(111, 255, 44), stop:1 rgb(186, 255, 82));\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.Searching.setFlat(True)
        self.Searching.setObjectName("Searching")
        self.Sorting = QtWidgets.QPushButton(self.centralwidget)
        self.Sorting.setGeometry(QtCore.QRect(10, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Sorting.setFont(font)
        self.Sorting.setStyleSheet("QPushButton{\n"
"    background-color:rgb(44, 130, 134);\n"
"}\n"
"QPushButton:hover{\n"
"    color: #0000;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgbargb(111, 255, 44), stop:1 rgb(186, 255, 82));\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.Sorting.setFlat(True)
        self.Sorting.setObjectName("Sorting")
        self.Scraping = QtWidgets.QPushButton(self.centralwidget)
        self.Scraping.setGeometry(QtCore.QRect(10, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Scraping.setFont(font)
        self.Scraping.setStyleSheet("QPushButton{\n"
"    background-color:rgb(44, 130, 134);\n"
"}\n"
"QPushButton:hover{\n"
"    color: #0000;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgbargb(111, 255, 44), stop:1 rgb(186, 255, 82));\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.Scraping.setFlat(True)
        self.Scraping.setObjectName("Scraping")
        self.heading_label = QtWidgets.QLabel(self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(60, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.heading_label.setFont(font)
        self.heading_label.setStyleSheet("color:(0,0,0,200);")
        self.heading_label.setObjectName("heading_label")
        self.frameSort = QtWidgets.QFrame(self.centralwidget)
        self.frameSort.setGeometry(QtCore.QRect(180, 0, 831, 491))
        self.frameSort.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSort.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSort.setObjectName("frameSort")
        self.frontlabel_2 = QtWidgets.QLabel(self.frameSort)
        self.frontlabel_2.setGeometry(QtCore.QRect(620, 10, 201, 471))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel_2.setFont(font)
        self.frontlabel_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(107, 255, 156), stop:1 rgb(121, 255, 251));\n"
"border-radius:15px;")
        self.frontlabel_2.setText("")
        self.frontlabel_2.setObjectName("frontlabel_2")
        self.lbl_logo = QtWidgets.QLabel(self.frameSort)
        self.lbl_logo.setGeometry(QtCore.QRect(260, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_logo.setFont(font)
        self.lbl_logo.setStyleSheet("color:rgb(0, 0, 0);\n"
"")
        self.lbl_logo.setObjectName("lbl_logo")
        self.label_17 = QtWidgets.QLabel(self.frameSort)
        self.label_17.setGeometry(QtCore.QRect(630, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.combo_algo_sort_2 = QtWidgets.QComboBox(self.frameSort)
        self.combo_algo_sort_2.setGeometry(QtCore.QRect(690, 100, 121, 22))
        self.combo_algo_sort_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_algo_sort_2.setObjectName("combo_algo_sort_2")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.combo_algo_sort_2.addItem("")
        self.col_fuel_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_fuel_2.setGeometry(QtCore.QRect(720, 290, 41, 16))
        self.col_fuel_2.setObjectName("col_fuel_2")
        self.btn_sort_2 = QtWidgets.QPushButton(self.frameSort)
        self.btn_sort_2.setGeometry(QtCore.QRect(640, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_sort_2.setFont(font)
        self.btn_sort_2.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_sort_2.setObjectName("btn_sort_2")
        self.col_name_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_name_2.setGeometry(QtCore.QRect(630, 210, 51, 21))
        self.col_name_2.setObjectName("col_name_2")
        self.col_mileage_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_mileage_2.setGeometry(QtCore.QRect(630, 290, 61, 21))
        self.col_mileage_2.setObjectName("col_mileage_2")
        self.radio_descend_sort_2 = QtWidgets.QRadioButton(self.frameSort)
        self.radio_descend_sort_2.setGeometry(QtCore.QRect(720, 150, 82, 17))
        self.radio_descend_sort_2.setObjectName("radio_descend_sort_2")
        self.col_grade_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_grade_2.setGeometry(QtCore.QRect(720, 210, 51, 21))
        self.col_grade_2.setObjectName("col_grade_2")
        self.btn_clr_sort_2 = QtWidgets.QPushButton(self.frameSort)
        self.btn_clr_sort_2.setGeometry(QtCore.QRect(720, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_clr_sort_2.setFont(font)
        self.btn_clr_sort_2.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_clr_sort_2.setObjectName("btn_clr_sort_2")
        self.col_cc_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_cc_2.setGeometry(QtCore.QRect(630, 330, 51, 21))
        self.col_cc_2.setObjectName("col_cc_2")
        self.col_link_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_link_2.setGeometry(QtCore.QRect(720, 330, 61, 21))
        self.col_link_2.setObjectName("col_link_2")
        self.label_14 = QtWidgets.QLabel(self.frameSort)
        self.label_14.setGeometry(QtCore.QRect(690, 30, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.col_year_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_year_2.setGeometry(QtCore.QRect(630, 250, 51, 21))
        self.col_year_2.setObjectName("col_year_2")
        self.radio_ascend_sort_2 = QtWidgets.QRadioButton(self.frameSort)
        self.radio_ascend_sort_2.setGeometry(QtCore.QRect(630, 150, 82, 17))
        self.radio_ascend_sort_2.setObjectName("radio_ascend_sort_2")
        self.col_trans_2 = QtWidgets.QCheckBox(self.frameSort)
        self.col_trans_2.setGeometry(QtCore.QRect(720, 250, 81, 16))
        self.col_trans_2.setObjectName("col_trans_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(190, 130, 601, 341))
        self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(8)
        # self.tableWidget.setRowCount(14)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(7, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(8, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(9, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(10, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(11, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(12, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(13, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(7, item)
        self.frameSearch = QtWidgets.QFrame(self.centralwidget)
        self.frameSearch.setGeometry(QtCore.QRect(180, 0, 831, 491))
        self.frameSearch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSearch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSearch.setObjectName("frameSearch")
        self.frontlabel_3 = QtWidgets.QLabel(self.frameSearch)
        self.frontlabel_3.setGeometry(QtCore.QRect(620, 10, 201, 471))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel_3.setFont(font)
        self.frontlabel_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(107, 255, 156), stop:1 rgb(121, 255, 251));\n"
"border-radius:15px;")
        self.frontlabel_3.setText("")
        self.frontlabel_3.setObjectName("frontlabel_3")
        self.lbl_logo_2 = QtWidgets.QLabel(self.frameSearch)
        self.lbl_logo_2.setGeometry(QtCore.QRect(260, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_logo_2.setFont(font)
        self.lbl_logo_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"")
        self.lbl_logo_2.setObjectName("lbl_logo_2")
        self.widget_4 = QtWidgets.QWidget(self.frameSearch)
        self.widget_4.setGeometry(QtCore.QRect(150, 70, 321, 41))
        self.widget_4.setStyleSheet("background-color:rgb(69, 255, 49);\n"
"border-radius:80px;")
        self.widget_4.setObjectName("widget_4")
        self.txt_car_contains = QtWidgets.QPlainTextEdit(self.widget_4)
        self.txt_car_contains.setGeometry(QtCore.QRect(10, 10, 211, 21))
        self.txt_car_contains.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:0px;")
        self.txt_car_contains.setObjectName("txt_car_contains")
        self.btn_car_contains = QtWidgets.QPushButton(self.widget_4)
        self.btn_car_contains.setGeometry(QtCore.QRect(230, 10, 75, 23))
        self.btn_car_contains.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(0,0,0);\n"
"color: rgb(255, 255, 255);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_car_contains.setObjectName("btn_car_contains")
        self.txt_start_search_2 = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_start_search_2.setGeometry(QtCore.QRect(680, 270, 121, 21))
        self.txt_start_search_2.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_start_search_2.setObjectName("txt_start_search_2")
        self.label_7 = QtWidgets.QLabel(self.frameSearch)
        self.label_7.setGeometry(QtCore.QRect(630, 240, 41, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frameSearch)
        self.label_8.setGeometry(QtCore.QRect(630, 270, 41, 21))
        self.label_8.setObjectName("label_8")
        self.radio_not_2 = QtWidgets.QCheckBox(self.frameSearch)
        self.radio_not_2.setGeometry(QtCore.QRect(630, 370, 51, 17))
        self.radio_not_2.setObjectName("radio_not_2")
        self.combo_attribute_search_2 = QtWidgets.QComboBox(self.frameSearch)
        self.combo_attribute_search_2.setGeometry(QtCore.QRect(690, 120, 121, 22))
        self.combo_attribute_search_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_attribute_search_2.setObjectName("combo_attribute_search_2")
        self.txt_col_contains_2 = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_col_contains_2.setGeometry(QtCore.QRect(680, 240, 121, 21))
        self.txt_col_contains_2.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_col_contains_2.setObjectName("txt_col_contains_2")
        self.txt_end_search_2 = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_end_search_2.setGeometry(QtCore.QRect(680, 300, 121, 21))
        self.txt_end_search_2.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_end_search_2.setObjectName("txt_end_search_2")
        self.combo_algo_search_2 = QtWidgets.QComboBox(self.frameSearch)
        self.combo_algo_search_2.setGeometry(QtCore.QRect(690, 160, 121, 22))
        self.combo_algo_search_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_algo_search_2.setObjectName("combo_algo_search_2")
        self.label_12 = QtWidgets.QLabel(self.frameSearch)
        self.label_12.setGeometry(QtCore.QRect(640, 200, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frameSearch)
        self.label_13.setGeometry(QtCore.QRect(630, 160, 61, 21))
        self.label_13.setObjectName("label_13")
        self.btn_clr_search_2 = QtWidgets.QPushButton(self.frameSearch)
        self.btn_clr_search_2.setGeometry(QtCore.QRect(730, 430, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_clr_search_2.setFont(font)
        self.btn_clr_search_2.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_clr_search_2.setObjectName("btn_clr_search_2")
        self.txt_or_col_2 = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_or_col_2.setGeometry(QtCore.QRect(680, 350, 121, 16))
        self.txt_or_col_2.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_or_col_2.setObjectName("txt_or_col_2")
        self.label_15 = QtWidgets.QLabel(self.frameSearch)
        self.label_15.setGeometry(QtCore.QRect(630, 300, 41, 21))
        self.label_15.setObjectName("label_15")
        self.btn_search_2 = QtWidgets.QPushButton(self.frameSearch)
        self.btn_search_2.setGeometry(QtCore.QRect(650, 430, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_search_2.setFont(font)
        self.btn_search_2.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_search_2.setObjectName("btn_search_2")
        self.txt_not_col_2 = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_not_col_2.setGeometry(QtCore.QRect(680, 371, 121, 16))
        self.txt_not_col_2.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_not_col_2.setObjectName("txt_not_col_2")
        self.radio_and_2 = QtWidgets.QCheckBox(self.frameSearch)
        self.radio_and_2.setGeometry(QtCore.QRect(630, 330, 51, 17))
        self.radio_and_2.setObjectName("radio_and_2")
        self.radio_or_2 = QtWidgets.QCheckBox(self.frameSearch)
        self.radio_or_2.setGeometry(QtCore.QRect(630, 350, 51, 17))
        self.radio_or_2.setObjectName("radio_or_2")
        self.label_16 = QtWidgets.QLabel(self.frameSearch)
        self.label_16.setGeometry(QtCore.QRect(690, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.txt_and_col_2 = QtWidgets.QTextEdit(self.frameSearch)
        self.txt_and_col_2.setGeometry(QtCore.QRect(680, 330, 121, 16))
        self.txt_and_col_2.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_and_col_2.setObjectName("txt_and_col_2")
        self.label_18 = QtWidgets.QLabel(self.frameSearch)
        self.label_18.setGeometry(QtCore.QRect(630, 120, 61, 21))
        self.label_18.setObjectName("label_18")
        self.txt_start_search = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_start_search.setGeometry(QtCore.QRect(830, 670, 121, 21))
        self.txt_start_search.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_start_search.setObjectName("txt_start_search")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(780, 640, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 670, 41, 21))
        self.label_6.setObjectName("label_6")
        self.radio_not = QtWidgets.QCheckBox(self.centralwidget)
        self.radio_not.setGeometry(QtCore.QRect(780, 770, 51, 17))
        self.radio_not.setObjectName("radio_not")
        self.combo_attribute_search = QtWidgets.QComboBox(self.centralwidget)
        self.combo_attribute_search.setGeometry(QtCore.QRect(840, 520, 121, 22))
        self.combo_attribute_search.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_attribute_search.setObjectName("combo_attribute_search")
        self.txt_col_contains = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_col_contains.setGeometry(QtCore.QRect(830, 640, 121, 21))
        self.txt_col_contains.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_col_contains.setObjectName("txt_col_contains")
        self.txt_end_search = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_end_search.setGeometry(QtCore.QRect(830, 700, 121, 21))
        self.txt_end_search.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_end_search.setObjectName("txt_end_search")
        self.combo_algo_search = QtWidgets.QComboBox(self.centralwidget)
        self.combo_algo_search.setGeometry(QtCore.QRect(840, 560, 121, 22))
        self.combo_algo_search.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.combo_algo_search.setObjectName("combo_algo_search")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(790, 600, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(780, 560, 61, 21))
        self.label_4.setObjectName("label_4")
        self.btn_clr_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clr_search.setGeometry(QtCore.QRect(880, 830, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_clr_search.setFont(font)
        self.btn_clr_search.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_clr_search.setObjectName("btn_clr_search")
        self.txt_or_col = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_or_col.setGeometry(QtCore.QRect(830, 750, 121, 16))
        self.txt_or_col.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_or_col.setObjectName("txt_or_col")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(780, 700, 41, 21))
        self.label_11.setObjectName("label_11")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(800, 830, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_search.setObjectName("btn_search")
        self.txt_not_col = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_not_col.setGeometry(QtCore.QRect(830, 771, 121, 16))
        self.txt_not_col.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_not_col.setObjectName("txt_not_col")
        self.radio_and = QtWidgets.QCheckBox(self.centralwidget)
        self.radio_and.setGeometry(QtCore.QRect(780, 730, 51, 17))
        self.radio_and.setObjectName("radio_and")
        self.radio_or = QtWidgets.QCheckBox(self.centralwidget)
        self.radio_or.setGeometry(QtCore.QRect(780, 750, 51, 17))
        self.radio_or.setObjectName("radio_or")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 520, 61, 21))
        self.label_3.setObjectName("label_3")
        self.txt_and_col = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_and_col.setGeometry(QtCore.QRect(830, 730, 121, 16))
        self.txt_and_col.setStyleSheet("background-color:rgb(255, 240, 255);\n"
"botder-radius:0px;")
        self.txt_and_col.setObjectName("txt_and_col")
        self.frameScrap = QtWidgets.QFrame(self.centralwidget)
        self.frameScrap.setGeometry(QtCore.QRect(180, 0, 831, 491))
        self.frameScrap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameScrap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameScrap.setObjectName("frameScrap")
        self.lbl_logo_3 = QtWidgets.QLabel(self.frameScrap)
        self.lbl_logo_3.setGeometry(QtCore.QRect(350, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_logo_3.setFont(font)
        self.lbl_logo_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"")
        self.lbl_logo_3.setObjectName("lbl_logo_3")
        self.frontlabel_4 = QtWidgets.QLabel(self.frameScrap)
        self.frontlabel_4.setGeometry(QtCore.QRect(90, 100, 611, 311))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.frontlabel_4.setFont(font)
        self.frontlabel_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(107, 255, 156), stop:1 rgb(121, 255, 251));\n"
"border-radius:15px;")
        self.frontlabel_4.setText("")
        self.frontlabel_4.setObjectName("frontlabel_4")
        self.label_19 = QtWidgets.QLabel(self.frameScrap)
        self.label_19.setGeometry(QtCore.QRect(270, 130, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lbl_entites_scrapped = QtWidgets.QLabel(self.frameScrap)
        self.lbl_entites_scrapped.setGeometry(QtCore.QRect(500, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_entites_scrapped.setFont(font)
        self.lbl_entites_scrapped.setObjectName("lbl_entites_scrapped")
        self.txt_url = QtWidgets.QPlainTextEdit(self.frameScrap)
        self.txt_url.setGeometry(QtCore.QRect(280, 210, 311, 31))
        self.txt_url.setStyleSheet("background-color:rgb(255,255,255);\n"
"border-radius:0px;")
        self.txt_url.setObjectName("txt_url")
        self.label_9 = QtWidgets.QLabel(self.frameScrap)
        self.label_9.setGeometry(QtCore.QRect(160, 210, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_20 = QtWidgets.QLabel(self.frameScrap)
        self.label_20.setGeometry(QtCore.QRect(160, 280, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.progressBar_scrap = QtWidgets.QProgressBar(self.frameScrap)
        self.progressBar_scrap.setGeometry(QtCore.QRect(280, 280, 341, 31))
        self.progressBar_scrap.setProperty("value", 24)
        self.progressBar_scrap.setObjectName("progressBar_scrap")
        self.btn_pause_scrap = QtWidgets.QPushButton(self.frameScrap)
        self.btn_pause_scrap.setGeometry(QtCore.QRect(350, 350, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_pause_scrap.setFont(font)
        self.btn_pause_scrap.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_pause_scrap.setObjectName("btn_pause_scrap")
        self.btn_scrap = QtWidgets.QPushButton(self.frameScrap)
        self.btn_scrap.setGeometry(QtCore.QRect(210, 352, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_scrap.setFont(font)
        self.btn_scrap.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_scrap.setObjectName("btn_scrap")
        self.btn_resume_scrap = QtWidgets.QPushButton(self.frameScrap)
        self.btn_resume_scrap.setGeometry(QtCore.QRect(490, 350, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(11)
        self.btn_resume_scrap.setFont(font)
        self.btn_resume_scrap.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 5px;\n"
"background-color: rgb(124, 203, 255);\n"
"}\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(240,248,255);\n"
"color: rgb(0,0,0);\n"
" }\n"
"QPushButton:pressed {\n"
"border: 1px solid rgb(24, 103, 155);\n"
"border-radius: 10px;\n"
"background-color: rgb(20, 153, 240);\n"
" }")
        self.btn_resume_scrap.setObjectName("btn_resume_scrap")
        self.framemain = QtWidgets.QFrame(self.centralwidget)
        self.framemain.setGeometry(QtCore.QRect(180, 10, 901, 491))
        self.framemain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framemain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framemain.setObjectName("framemain")
        self.label = QtWidgets.QLabel(self.framemain)
        self.label.setGeometry(QtCore.QRect(110, 120, 661, 161))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.framemain)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_21 = QtWidgets.QLabel(self.framemain)
        self.label_21.setGeometry(QtCore.QRect(650, 130, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.framemain)
        self.label_22.setGeometry(QtCore.QRect(270, 350, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.backlabel.raise_()
        self.framemain.raise_()
        self.frontlabel.raise_()
        self.Searching.raise_()
        self.Sorting.raise_()
        self.Scraping.raise_()
        self.heading_label.raise_()
        self.frameSort.raise_()
        self.tableWidget.raise_()
        self.frameSearch.raise_()
        self.txt_start_search.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.radio_not.raise_()
        self.combo_attribute_search.raise_()
        self.txt_col_contains.raise_()
        self.txt_end_search.raise_()
        self.combo_algo_search.raise_()
        self.label_10.raise_()
        self.label_4.raise_()
        self.btn_clr_search.raise_()
        self.txt_or_col.raise_()
        self.label_11.raise_()
        self.btn_search.raise_()
        self.txt_not_col.raise_()
        self.radio_and.raise_()
        self.radio_or.raise_()
        self.label_3.raise_()
        self.txt_and_col.raise_()
        self.frameScrap.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Searching.setText(_translate("MainWindow", "Searching"))
        self.Sorting.setText(_translate("MainWindow", "Sorting"))
        self.Scraping.setText(_translate("MainWindow", "Scraping"))
        self.heading_label.setText(_translate("MainWindow", "Menu"))
        self.lbl_logo.setText(_translate("MainWindow", "Sorting"))
        self.label_17.setText(_translate("MainWindow", "Algorithm"))
        self.combo_algo_sort_2.setItemText(0, _translate("MainWindow", "Merge Sort"))
        self.combo_algo_sort_2.setItemText(1, _translate("MainWindow", "Selection Sort "))
        self.combo_algo_sort_2.setItemText(2, _translate("MainWindow", "Insertion Sort"))
        self.combo_algo_sort_2.setItemText(3, _translate("MainWindow", "Bubble Sort"))
        self.combo_algo_sort_2.setItemText(4, _translate("MainWindow", "Quick Sort"))
        self.combo_algo_sort_2.setItemText(5, _translate("MainWindow", "Radix Sort"))
        self.combo_algo_sort_2.setItemText(6, _translate("MainWindow", "Bucket Sort"))
        self.combo_algo_sort_2.setItemText(7, _translate("MainWindow", "Counting Sort"))
        self.combo_algo_sort_2.setItemText(8, _translate("MainWindow", "Heap Sort"))
        self.combo_algo_sort_2.setItemText(9, _translate("MainWindow", "Shell Sort"))
        self.combo_algo_sort_2.setItemText(10, _translate("MainWindow", "Comb Sort"))
        self.col_fuel_2.setText(_translate("MainWindow", "na"))
        self.btn_sort_2.setText(_translate("MainWindow", "Sort"))
        self.col_name_2.setText(_translate("MainWindow", "na"))
        self.col_mileage_2.setText(_translate("MainWindow", "na"))
        self.radio_descend_sort_2.setText(_translate("MainWindow", "Descending"))
        self.col_grade_2.setText(_translate("MainWindow", "na"))
        self.btn_clr_sort_2.setText(_translate("MainWindow", "Clear"))
        self.col_cc_2.setText(_translate("MainWindow", "na"))
        self.col_link_2.setText(_translate("MainWindow", "na"))
        self.label_14.setText(_translate("MainWindow", "Sorting"))
        self.col_year_2.setText(_translate("MainWindow", "na"))
        self.radio_ascend_sort_2.setText(_translate("MainWindow", "Ascending"))
        self.col_trans_2.setText(_translate("MainWindow", "na"))
        # item = self.tableWidget.verticalHeaderItem(0)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(1)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(2)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(3)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(4)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(5)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(6)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(7)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(8)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(9)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(10)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(11)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(12)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.verticalHeaderItem(13)
        # item.setText(_translate("MainWindow", "New Row"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "New Column"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "New Column"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "New Column"))
        # item = self.tableWidget.horizontalHeaderItem(3)
        # item.setText(_translate("MainWindow", "New Column"))
        # item = self.tableWidget.horizontalHeaderItem(4)
        # item.setText(_translate("MainWindow", "New Column"))
        # item = self.tableWidget.horizontalHeaderItem(5)
        # item.setText(_translate("MainWindow", "New Column"))
        # item = self.tableWidget.horizontalHeaderItem(6)
        # item.setText(_translate("MainWindow", "New Column"))
        # item = self.tableWidget.horizontalHeaderItem(7)
        # item.setText(_translate("MainWindow", "New Column"))
        self.lbl_logo_2.setText(_translate("MainWindow", "Search"))
        self.btn_car_contains.setText(_translate("MainWindow", "Search "))
        self.label_7.setText(_translate("MainWindow", "Contains"))
        self.label_8.setText(_translate("MainWindow", "Start as"))
        self.radio_not_2.setText(_translate("MainWindow", "NOT"))
        self.label_12.setText(_translate("MainWindow", "Filters"))
        self.label_13.setText(_translate("MainWindow", "Algorithm"))
        self.btn_clr_search_2.setText(_translate("MainWindow", "Clear"))
        self.label_15.setText(_translate("MainWindow", "End as"))
        self.btn_search_2.setText(_translate("MainWindow", "Search"))
        self.radio_and_2.setText(_translate("MainWindow", "AND"))
        self.radio_or_2.setText(_translate("MainWindow", "OR"))
        self.label_16.setText(_translate("MainWindow", "Searching "))
        self.label_18.setText(_translate("MainWindow", "Attribute"))
        self.label_5.setText(_translate("MainWindow", "Contains"))
        self.label_6.setText(_translate("MainWindow", "Start as"))
        self.radio_not.setText(_translate("MainWindow", "NOT"))
        self.label_10.setText(_translate("MainWindow", "Filters"))
        self.label_4.setText(_translate("MainWindow", "Algorithm"))
        self.btn_clr_search.setText(_translate("MainWindow", "Clear"))
        self.label_11.setText(_translate("MainWindow", "End as"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.radio_and.setText(_translate("MainWindow", "AND"))
        self.radio_or.setText(_translate("MainWindow", "OR"))
        self.label_3.setText(_translate("MainWindow", "Attribute"))
        self.lbl_logo_3.setText(_translate("MainWindow", "Scraping"))
        self.label_19.setText(_translate("MainWindow", "Entities Scrapped:"))
        self.lbl_entites_scrapped.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "URL:"))
        self.label_20.setText(_translate("MainWindow", "Progress:"))
        self.btn_pause_scrap.setText(_translate("MainWindow", "Pause"))
        self.btn_scrap.setText(_translate("MainWindow", "Scrap"))
        self.btn_resume_scrap.setText(_translate("MainWindow", "Resume"))
        self.label.setText(_translate("MainWindow", "\n"
"Welcome To:\n"
"\n"
"         Stack Exchange Analyser 🖥"))
        self.label_2.setText(_translate("MainWindow", "🎈🎈🎈🎈"))
        self.label_21.setText(_translate("MainWindow", "🎈🎈🎈🎈"))
        self.label_22.setText(_translate("MainWindow", "🎉🎉🎉🎉🎉🎉"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
